### ISSUE TITLE
Repositories cleaning

### ISSUE THREAD

**Issue by andresmoschini** [MakingSense/Wordpress-Plugin-Doppler#1]
@dnoya, @easla do you think that is it possible to delete this repository or make it public? We have no more private repositories available at Making Sense and we need to do some cleaning.

BTW, What a weird repository! Is it completely anonymous?

![image](https://user-images.githubusercontent.com/1157864/37983738-a4acd192-31ca-11e8-8442-e377d641c0ed.png)

**Comment by lmarquezMS** [comment]
Hi @andresmoschini , I made all those but I don't know why I 'm not as the author. 

BTW, I don't know how is the progress of the new version of the plugin but I think that there isn't a repository in the making sense account. 

Here are my last [changes](https://github.com/lmarquezMS/Doppler_WP_plugin/tree/develop)

**Comment by andresmoschini** [comment]
So, as I understand this repository is deprecated since https://github.com/lmarquezMS/Doppler_WP_plugin seems to be newer.

Also, the repository in your account seems to be public. 

@lmarquezMS, what do you recommend? should I delete it? should I make it public?

BTW, maybe you should transfer ownership of your repository to MakingSense, or at least we should create a fork in MakingSense, right?

**Comment by lmarquezMS** [comment]
IMO I'd leave it as a public repository.

I can't see sense to maintain this repository given that the code is public in the Wordpress store.

> BTW, maybe you should transfer ownership of your repository to MakingSense, or at least we should create a fork in MakingSense, right?

I have not problem with any of those choises.

**Comment by andresmoschini** [comment]
Great! in the meantime someone made it public.
